pipeline:
  name: parentChainPipelineInputSet
  identifier: ParentPipelineZ7n9kJu812
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        type: Pipeline
        spec:
          org: Simlified_Git_sync
          pipeline: pl_auto_pipeline_Dljkc
          project: SimplifiedGitSync_Do_Not_Delete
          inputSetReferences:
            - pl_auto_inputset_Z4y0X