pipeline:
  name: parentChainPipelineInputSet
  identifier: ParentPipelineF9VD0wy2u1
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        type: Pipeline
        spec:
          org: Simlified_Git_sync
          pipeline: pl_auto_pipeline_SVBj2
          project: SimplifiedGitSync_Do_Not_Delete
          inputSetReferences:
            - pl_auto_inputset_6pvPN