pipeline:
  name: remote_multi_svc_env_infra_pipebCQ0z
  identifier: remote_multi_svc_env_infra_pipebCQ0z
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: remote_multi_svc_env_infra_tempukYD3
          versionLabel: v1
          gitBranch: main
