pipeline:
  name: remote_multi_svc_env_infra_pipeWObL3
  identifier: remote_multi_svc_env_infra_pipeWObL3
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: remote_multi_svc_env_infra_tempcytzr
          versionLabel: v1
          gitBranch: main
