pipeline:
  name: remote_svc_env_infra_pipeO6VyC
  identifier: remote_svc_env_infra_pipeO6VyC
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: remote_svc_env_infra_tempve5WF
          versionLabel: v1
          gitBranch: main
