service:
  name: NGPipeAutotXM71q5P7G
  identifier: NGPipeAutotXM71q5P7G
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcWf3YfVfeBl
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
