service:
  name: NGPipeAutoJnRP4PDFCy
  identifier: NGPipeAutoJnRP4PDFCy
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
