infrastructureDefinition:
  name: NGPipeAutooLpxXl7R2J
  identifier: NGPipeAutooLpxXl7R2J
  environmentRef: NGPipeAutoki1SXmysi1
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
