infrastructureDefinition:
  name: NGPipeAutoAgHuFEazP0
  identifier: NGPipeAutoAgHuFEazP0
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoRp1MXx5X7y
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
