environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesSTcOUPphhO
  identifier: NGPipeAutotE7oSHL74h
  tags: {}
  name: NGPipeAutotE7oSHL74h
  type: PreProduction
