infrastructureDefinition:
  name: NGPipeAutoG88sOcBY3E
  identifier: NGPipeAutoG88sOcBY3E
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraeD5IzQi0y0
  environmentRef: NGPipeAutotjwOLeR33F
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
