service:
  name: NGPipeAutoQ0hlE0K8ry
  identifier: NGPipeAutoQ0hlE0K8ry
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcWf3YfVfeBl
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
