service:
  name: NGPipeAutopJ9GQiaBLd
  identifier: NGPipeAutopJ9GQiaBLd
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
