template:
  name: NGPipeAutoPipelineTempETrIxL6TZj
  identifier: NGPipeAutoPipelineTempETrIxL6TZj
  projectIdentifier: NGPipeAutoPipelineSvcIKSred3T0i
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Pipeline
  tags: {}
  spec:
    stages:
      - stage:
          name: s1
          identifier: s1
          tags: {}
          template:
            templateRef: NGPipeAutoStageTemp2nmcoN6kvY
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                execution:
                  steps:
                    - step:
                        identifier: s1
                        template:
                          templateInputs:
                            type: ShellScript
                            timeout: <+input>
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
      - stage:
          name: s2
          identifier: s2
          tags: {}
          template:
            templateRef: NGPipeAutoStageTempw5w4iGD5eT
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                execution:
                  steps:
                    - step:
                        identifier: s1
                        template:
                          templateInputs:
                            type: ShellScript
                            timeout: <+input>
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
    allowStageExecutions: true

