environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  identifier: NGPipeAutoQoyLIWfGFz
  tags: {}
  name: NGPipeAutoQoyLIWfGFz
  type: PreProduction
