infrastructureDefinition:
  name: NGPipeAutoBiu074miAp
  identifier: NGPipeAutoBiu074miAp
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  environmentRef: NGPipeAutoSYJOmEaIb5
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
