infrastructureDefinition:
  name: NGPipeAutoFWpp1zDILm
  identifier: NGPipeAutoFWpp1zDILm
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  environmentRef: NGPipeAutofLfgOROfN3
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
