infrastructureDefinition:
  name: NGPipeAutogH3Z8BgvET
  identifier: NGPipeAutogH3Z8BgvET
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  environmentRef: NGPipeAutonB5mo7owCR
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
