environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesg6FQC12PCB
  identifier: NGPipeAutozlnANpklTI
  tags: {}
  name: NGPipeAutozlnANpklTI
  type: PreProduction
