service:
  name: NGPipeAutoSvcv92TfSOX8J
  identifier: NGPipeAutoSvcv92TfSOX8J
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
