environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  identifier: NGPipeAuto2y6GdhfMoz
  tags: {}
  name: NGPipeAuto2y6GdhfMoz
  type: PreProduction
