service:
  name: NGPipeAutoSvcCr1Nn3fy1J
  identifier: NGPipeAutoSvcCr1Nn3fy1J
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
