environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcPodUfSK16G
  identifier: NGPipeAutoeF1Pi5pT5t
  tags: {}
  name: NGPipeAutoeF1Pi5pT5t
  type: PreProduction
