template:
  name: NGPipeAutoPipelineTempiGf2CI3X42
  identifier: NGPipeAutoPipelineTempiGf2CI3X42
  projectIdentifier: NGPipeAutoPipelineSvckLDEQQthi2
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Pipeline
  tags: {}
  spec:
    stages:
      - stage:
          name: s1
          identifier: s1
          tags: {}
          template:
            templateRef: NGPipeAutoStageTempwk3xNuNLjp
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
      - stage:
          name: s2
          identifier: s2
          tags: {}
          template:
            templateRef: NGPipeAutoStageTempuExU82xogu
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
    allowStageExecutions: true
