service:
  name: NGPipeAutodNLcoeavp5
  identifier: NGPipeAutodNLcoeavp5
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
