infrastructureDefinition:
  name: NGPipeAutovh1NDETRIP
  identifier: NGPipeAutovh1NDETRIP
  environmentRef: NGPipeAutopRb6q4eDL2
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
