environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrarPaZmmrG7i
  identifier: NGPipeAutojxUrKehDOD
  tags: {}
  name: NGPipeAutojxUrKehDOD
  type: PreProduction
