environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcPodUfSK16G
  identifier: NGPipeAuto7ztByiGP9v
  tags: {}
  name: NGPipeAuto7ztByiGP9v
  type: PreProduction
