environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraFlbGm5NRGb
  identifier: NGPipeAutoAAmrkjN7HU
  tags: {}
  name: NGPipeAutoAAmrkjN7HU
  type: PreProduction
