environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  identifier: NGPipeAutoLGgjtTMmO8
  tags: {}
  name: NGPipeAutoLGgjtTMmO8
  type: PreProduction
