infrastructureDefinition:
  name: NGPipeAutoMJRVahMWwm
  identifier: NGPipeAutoMJRVahMWwm
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  environmentRef: NGPipeAuto2y6GdhfMoz
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
