environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraeD5IzQi0y0
  identifier: NGPipeAutoHHa7G9fUqR
  tags: {}
  name: NGPipeAutoHHa7G9fUqR
  type: PreProduction
