service:
  name: NGPipeAutoSvcTvrIAhmqim
  identifier: NGPipeAutoSvcTvrIAhmqim
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
