template:
  name: NGPipeAutoStepTemp8qW1PGti5U
  identifier: NGPipeAutoStepTemp8qW1PGti5U
  projectIdentifier: NGPipeAutoPipelineSvcIKSred3T0i
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Step
  tags: {}
  spec:
    timeout: 10m
    type: ShellScript
    spec:
      shell: Bash
      onDelegate: true
      source:
        type: Inline
        spec:
          script: echo Hello
      environmentVariables: []
      outputVariables: []
