template:
  name: NGPipeAutoPipelineTempDOboQvfI8e
  identifier: NGPipeAutoPipelineTempDOboQvfI8e
  projectIdentifier: NGPipeAutoPipelineSvcIKSred3T0i
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Pipeline
  tags: {}
  spec:
    stages:
      - stage:
          name: s1
          identifier: s1
          tags: {}
          template:
            templateRef: NGPipeAutoStageTempUXOWGmBm73
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
      - stage:
          name: s2
          identifier: s2
          tags: {}
          template:
            templateRef: NGPipeAutoStageTemprhG1cFujGK
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
    allowStageExecutions: true
