template:
  name: NGPipeAutoStageTempPsFHNFJr6Q
  identifier: NGPipeAutoStageTempPsFHNFJr6Q
  projectIdentifier: NGPipeAutoPipelineSvcxaNj4ORrVA
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Stage
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      environment:
        environmentRef: <+input>
        deployToAll: false
        environmentInputs: <+input>
        serviceOverrideInputs: <+input>
        infrastructureDefinitions: <+input>
      service:
        serviceRef: NGPipeAutoSvcbwntbLhKLX
        serviceInputs:
          serviceDefinition:
            type: Kubernetes
            spec:
              variables:
                - name: var1
                  type: String
                  default: "False"
                  value: <+input>.default(False).allowedValues(True,False,None)
      execution:
        steps:
          - step:
              type: ShellScript
              name: ShellScript_1
              identifier: ShellScript_1
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: exit 0
                environmentVariables: []
                outputVariables: []
              timeout: 10m
        rollbackSteps: []
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: MarkAsFailure
