template:
  name: remote_multi_svc_env_infra_tempgfIpi
  identifier: remote_multi_svc_env_infra_tempgfIpi
  versionLabel: v1
  type: Stage
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      execution:
        steps:
          - step:
              type: ShellScript
              name: ShellScript_1
              identifier: ShellScript_1
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: echo "hi"
                environmentVariables: []
                outputVariables: []
              timeout: 10m
        rollbackSteps: []
      services:
        values:
          - serviceRef: NGPipeAutoSvcTvrIAhmqim
          - serviceRef: NGPipeAutoSvcM6TvOc91JE
        metadata:
          parallel: true
      environments:
        metadata:
          parallel: true
        values:
          - environmentRef: NGPipeAutoQoyLIWfGFz
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAuto7YYfUJlYKp
          - environmentRef: NGPipeAutoLGgjtTMmO8
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoDiqbzJ9YwE
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: MarkAsFailure
