environment:
  name: NGPipeAutobb4oB7D8Tk
  identifier: NGPipeAutobb4oB7D8Tk
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcIuBZ2brX04
  tags: {
    }
  type: Production
