environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  identifier: NGPipeAutoVpRoiou7MI
  tags: {}
  name: NGPipeAutoVpRoiou7MI
  type: PreProduction
