template:
  name: NGPipeAutoStageTempdYBnSyou3Z
  identifier: NGPipeAutoStageTempdYBnSyou3Z
  projectIdentifier: NGPipeAutoPipelineSvcxaNj4ORrVA
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Stage
  tags: {}
  spec:
    type: Custom
    spec:
      execution:
        steps:
          - step:
              name: s1
              identifier: s1
              template:
                templateRef: NGPipeAutoStepTempsQRDpihUZt
                versionLabel: v1
                templateInputs:
                  type: ShellScript
                  timeout: <+input>
      environment:
        environmentRef: <+input>
        deployToAll: false
        environmentInputs: <+input>
        infrastructureDefinitions: <+input>
