service:
  name: NGPipeAutoDMFJcmJypo
  identifier: NGPipeAutoDMFJcmJypo
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcLubu6bhFHp
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
