environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesttSgrzwfLC
  identifier: NGPipeAutoDxEvDOsDHb
  tags: {}
  name: NGPipeAutoDxEvDOsDHb
  type: PreProduction
