environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  identifier: NGPipeAuto4ssjHqvPpU
  tags: {}
  name: NGPipeAuto4ssjHqvPpU
  type: PreProduction
