service:
  name: NGPipeAutoSvcaXbZLsFDtx
  identifier: NGPipeAutoSvcaXbZLsFDtx
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcPodUfSK16G
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
