service:
  name: NGPipeAutoQ6ZSaGbj49
  identifier: NGPipeAutoQ6ZSaGbj49
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
