infrastructureDefinition:
  name: NGPipeAutoDiqbzJ9YwE
  identifier: NGPipeAutoDiqbzJ9YwE
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  environmentRef: NGPipeAutoLGgjtTMmO8
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
