service:
  name: NGPipeAutowuASwBqqIT
  identifier: NGPipeAutowuASwBqqIT
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
