infrastructureDefinition:
  name: NGPipeAutoFcKlg3axIM
  identifier: NGPipeAutoFcKlg3axIM
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraFlbGm5NRGb
  environmentRef: NGPipeAutogtjIymeK5K
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
