infrastructureDefinition:
  name: NGPipeAutotkBg6DoQPG
  identifier: NGPipeAutotkBg6DoQPG
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraeD5IzQi0y0
  environmentRef: NGPipeAutoHHa7G9fUqR
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
