environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesSTcOUPphhO
  identifier: NGPipeAutoHoqEMYK7ga
  tags: {}
  name: NGPipeAutoHoqEMYK7ga
  type: PreProduction
