infrastructureDefinition:
  name: NGPipeAutoppjOYSDqGi
  identifier: NGPipeAutoppjOYSDqGi
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraIjIIdSrxgD
  environmentRef: NGPipeAutoVV6enz4zqs
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
