infrastructureDefinition:
  name: NGPipeAutouZdmwCwzF6
  identifier: NGPipeAutouZdmwCwzF6
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  environmentRef: NGPipeAutoCFYxcOtMlr
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
