environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfranhV9qcEBGD
  identifier: NGPipeAuto5l73TfPgxC
  tags: {}
  name: NGPipeAuto5l73TfPgxC
  type: PreProduction
