infrastructureDefinition:
  name: NGPipeAutoJtfaOBpdZH
  identifier: NGPipeAutoJtfaOBpdZH
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  environmentRef: NGPipeAutoLZNjG0vdlb
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
