infrastructureDefinition:
  name: NGPipeAutoAmt6662WFK
  identifier: NGPipeAutoAmt6662WFK
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoNV7Ktqjhsu
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
