infrastructureDefinition:
  name: NGPipeAutoHjYbiJyuwU
  identifier: NGPipeAutoHjYbiJyuwU
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  environmentRef: NGPipeAutoX8bDrn6J8t
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
