infrastructureDefinition:
  name: NGPipeAutojWG0l0uddo
  identifier: NGPipeAutojWG0l0uddo
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoofCqA8bdt7
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
