environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  identifier: NGPipeAutoSYJOmEaIb5
  tags: {}
  name: NGPipeAutoSYJOmEaIb5
  type: PreProduction
