environment:
  name: NGPipeAutoQ0tR42EvBH
  identifier: NGPipeAutoQ0tR42EvBH
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcIuBZ2brX04
  tags: {
    }
  type: Production
