pipeline:
  name: NGPipeAutoNGPipelinev8oqP7rojk
  identifier: NGPipeAutoNGPipelinev8oqP7rojk
  projectIdentifier: NGPipeAutoPipelineSvcji2SksktvH
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  tags: {}
  template:
    templateRef: NGPipeAutoPipelineTempA2X8SYCjsg
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: s1
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: s1
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    infrastructureDefinitions: <+input>
        - stage:
            identifier: s2
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: s1
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    infrastructureDefinitions: <+input>
