infrastructureDefinition:
  name: NGPipeAuto77n6ueOV1e
  identifier: NGPipeAuto77n6ueOV1e
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoudqrHH6wr4
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
