environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesJxSdCkeiTX
  identifier: NGPipeAutoYpiVQhQPUQ
  tags: {}
  name: NGPipeAutoYpiVQhQPUQ
  type: PreProduction
