template:
  name: NGPipeAutoPipelineTempVL5bJWgTAu
  identifier: NGPipeAutoPipelineTempVL5bJWgTAu
  projectIdentifier: NGPipeAutoPipelineSvcxaNj4ORrVA
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Pipeline
  tags: {}
  spec:
    stages:
      - stage:
          name: s1
          identifier: s1
          tags: {}
          template:
            templateRef: NGPipeAutoStageTempGJtrkpGopm
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                execution:
                  steps:
                    - step:
                        identifier: s1
                        template:
                          templateInputs:
                            type: ShellScript
                            timeout: <+input>
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
      - stage:
          name: s2
          identifier: s2
          tags: {}
          template:
            templateRef: NGPipeAutoStageTempK9hcORzQ4t
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                execution:
                  steps:
                    - step:
                        identifier: s1
                        template:
                          templateInputs:
                            type: ShellScript
                            timeout: <+input>
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
    allowStageExecutions: true

