infrastructureDefinition:
  name: NGPipeAutogSytxmJMw2
  identifier: NGPipeAutogSytxmJMw2
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfranhV9qcEBGD
  environmentRef: NGPipeAuto77UIlXIDh2
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
