template:
  name: NGPipeAutoStepTempHYks15Thmd
  identifier: NGPipeAutoStepTempHYks15Thmd
  projectIdentifier: NGPipeAutoPipelineSvcji2SksktvH
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Step
  tags: {}
  spec:
    timeout: <+input>
    type: ShellScript
    spec:
      shell: Bash
      onDelegate: true
      source:
        type: Inline
        spec:
          script: echo Hello
      environmentVariables: []
      outputVariables: []
