service:
  name: NGPipeAutoWzcyCbrVwU
  identifier: NGPipeAutoWzcyCbrVwU
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
