environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  identifier: NGPipeAutoX8bDrn6J8t
  tags: {}
  name: NGPipeAutoX8bDrn6J8t
  type: PreProduction
