environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  identifier: NGPipeAutoLZNjG0vdlb
  tags: {}
  name: NGPipeAutoLZNjG0vdlb
  type: PreProduction
