template:
  name: remote_svc_env_infra_temps0znC
  identifier: remote_svc_env_infra_temps0znC
  versionLabel: v1
  type: Stage
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      service:
        serviceRef: NGPipeAutoSvc65PWQQYnHG
        serviceInputs:
          serviceDefinition:
            type: Kubernetes
            spec:
              artifacts:
                primary:
                  sources:
                    - identifier: artifactId
                      type: Gcr
                      spec:
                        tag: "80"
      environments:
        metadata:
          parallel: true
        values:
          - environmentRef: NGPipeAuto2y6GdhfMoz
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoMJRVahMWwm
                inputs:
                  identifier: NGPipeAutoMJRVahMWwm
                  type: KubernetesDirect
                  spec:
                    namespace: default
      execution:
        steps:
          - step:
              name: Rollout Deployment
              identifier: rolloutDeployment
              type: K8sRollingDeploy
              timeout: 10m
              spec:
                skipDryRun: false
                pruningEnabled: false
        rollbackSteps:
          - step:
              name: Rollback Rollout Deployment
              identifier: rollbackRolloutDeployment
              type: K8sRollingRollback
              timeout: 10m
              spec:
                pruningEnabled: false
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: StageRollback
