environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  identifier: NGPipeAutoJxKcKjvxPl
  tags: {}
  name: NGPipeAutoJxKcKjvxPl
  type: PreProduction
