infrastructureDefinition:
  name: NGPipeAutotzBbA146Ox
  identifier: NGPipeAutotzBbA146Ox
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcPodUfSK16G
  environmentRef: NGPipeAuto7ztByiGP9v
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
