infrastructureDefinition:
  name: NGPipeAutoGsR24qKE4m
  identifier: NGPipeAutoGsR24qKE4m
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutod3FSRYmeYx
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
