template:
  name: NGPipeAutoStepTempsel3K34koL
  identifier: NGPipeAutoStepTempsel3K34koL
  projectIdentifier: NGPipeAutoPipelineSvckLDEQQthi2
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Step
  tags: {}
  spec:
    timeout: <+input>
    type: ShellScript
    spec:
      shell: Bash
      onDelegate: true
      source:
        type: Inline
        spec:
          script: echo Hello
      environmentVariables: []
      outputVariables: []
