pipeline:
  name: NGPipeAutoNGPipelinezXi4gSc9aT
  identifier: NGPipeAutoNGPipelinezXi4gSc9aT
  projectIdentifier: NGPipeAutoPipelineSvckLDEQQthi2
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  tags: {}
  template:
    templateRef: NGPipeAutoPipelineTempiGf2CI3X42
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: s1
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: s1
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    infrastructureDefinitions: <+input>
        - stage:
            identifier: s2
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: s1
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    infrastructureDefinitions: <+input>
