template:
  name: remote_multi_svc_env_infra_tempjRDmd
  identifier: remote_multi_svc_env_infra_tempjRDmd
  versionLabel: v1
  type: Stage
  projectIdentifier: NGPipeAutoPipelineSvcPodUfSK16G
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      execution:
        steps:
          - step:
              type: ShellScript
              name: ShellScript_1
              identifier: ShellScript_1
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: echo "hi"
                environmentVariables: []
                outputVariables: []
              timeout: 10m
        rollbackSteps: []
      services:
        values:
          - serviceRef: NGPipeAutoSvc00W3PDkHA4
          - serviceRef: NGPipeAutoSvcWoDd1QYKgq
        metadata:
          parallel: true
      environments:
        metadata:
          parallel: true
        values:
          - environmentRef: NGPipeAutomK1xvyV9OQ
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAuto9ERZFZIMyr
          - environmentRef: NGPipeAutohMoPzbA3Ju
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoovRWGYZrTA
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: MarkAsFailure
