infrastructureDefinition:
  name: NGPipeAutolSzw1cf8od
  identifier: NGPipeAutolSzw1cf8od
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrarPaZmmrG7i
  environmentRef: NGPipeAutoaHxbPOAzCY
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
