template:
  name: NGPipeAutoStepTemp9w97q53LSM
  identifier: NGPipeAutoStepTemp9w97q53LSM
  projectIdentifier: NGPipeAutoPipelineSvcxaNj4ORrVA
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Step
  tags: {}
  spec:
    timeout: 10m
    type: ShellScript
    spec:
      shell: Bash
      onDelegate: true
      source:
        type: Inline
        spec:
          script: echo Hello
      environmentVariables: []
      outputVariables: []
