pipeline:
  name: remote_svc_env_infra_pipeliEkQ
  identifier: remote_svc_env_infra_pipeliEkQ
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: NGPipeAutoSvcn43J4V7F2q
            gitBranch: main-patch
          environment:
            environmentRef: NGPipeAutoL2SKdZBJSN
            gitBranch: main-patch
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutogfzl3g0cbj
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hi"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
