service:
  name: NGPipeAutoZxg8u8rRZL
  identifier: NGPipeAutoZxg8u8rRZL
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcdgi0AmzdLQ
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
