template:
  name: remote_multi_svc_env_infra_tempfEpGM
  identifier: remote_multi_svc_env_infra_tempfEpGM
  versionLabel: v1
  type: Stage
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      execution:
        steps:
          - step:
              type: ShellScript
              name: ShellScript_1
              identifier: ShellScript_1
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: echo "hi"
                environmentVariables: []
                outputVariables: []
              timeout: 10m
        rollbackSteps: []
      services:
        values:
          - serviceRef: NGPipeAutoSvc2AG1lvU9I6
          - serviceRef: NGPipeAutoSvcwem4yQvnub
        metadata:
          parallel: true
      environments:
        metadata:
          parallel: true
        values:
          - environmentRef: NGPipeAutousolrDbtEf
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAuto5yheoXgdhr
          - environmentRef: NGPipeAutoQeT3oSV9ah
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoPNrp2IwVby
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: MarkAsFailure
