template:
  name: NGPipeAutoPipelineTempH1GHfZV6pZ
  identifier: NGPipeAutoPipelineTempH1GHfZV6pZ
  projectIdentifier: NGPipeAutoPipelineSvczuMGraajJ8
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Pipeline
  tags: {}
  spec:
    stages:
      - stage:
          name: s1
          identifier: s1
          tags: {}
          template:
            templateRef: NGPipeAutoStageTemp5vfy4ZoJy4
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
      - stage:
          name: s2
          identifier: s2
          tags: {}
          template:
            templateRef: NGPipeAutoStageTempi2hm1U3TdZ
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
    allowStageExecutions: true
