service:
  name: NGPipeAutoMbFPCu55LW
  identifier: NGPipeAutoMbFPCu55LW
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
