infrastructureDefinition:
  name: NGPipeAuto3j3VtZ29VK
  identifier: NGPipeAuto3j3VtZ29VK
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  environmentRef: NGPipeAuto7ZwDGwoDYD
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
