template:
  name: NGPipeAutoStepTempeiEVH07B4X
  identifier: NGPipeAutoStepTempeiEVH07B4X
  projectIdentifier: NGPipeAutoPipelineSvcIKSred3T0i
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Step
  tags: {}
  spec:
    timeout: 10m
    type: ShellScript
    spec:
      shell: Bash
      onDelegate: true
      source:
        type: Inline
        spec:
          script: echo Hello
      environmentVariables: []
      outputVariables: []
