service:
  name: NGPipeAutoQGnj5c1WO0
  identifier: NGPipeAutoQGnj5c1WO0
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
