template:
  name: remote_multi_svc_env_infra_tempynIag
  identifier: remote_multi_svc_env_infra_tempynIag
  versionLabel: v1
  type: Stage
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      execution:
        steps:
          - step:
              type: ShellScript
              name: ShellScript_1
              identifier: ShellScript_1
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: echo "hi"
                environmentVariables: []
                outputVariables: []
              timeout: 10m
        rollbackSteps: []
      services:
        values:
          - serviceRef: NGPipeAutoSvcCr1Nn3fy1J
          - serviceRef: NGPipeAutoSvcHZeklk910M
        metadata:
          parallel: true
      environments:
        metadata:
          parallel: true
        values:
          - environmentRef: NGPipeAutoCFYxcOtMlr
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutouZdmwCwzF6
          - environmentRef: NGPipeAutosJA9rV65Ov
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoATR3Q8skGB
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: MarkAsFailure
