service:
  name: NGPipeAutoSvcqMeNtmuHQ4
  identifier: NGPipeAutoSvcqMeNtmuHQ4
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
