environment:
  name: NGPipeAuto6okjJlS0DZ
  identifier: NGPipeAuto6okjJlS0DZ
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvciAupMU0cLL
  tags: {
    }
  type: Production
