environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  identifier: NGPipeAutozO85cJBIvs
  tags: {}
  name: NGPipeAutozO85cJBIvs
  type: PreProduction
