service:
  name: NGPipeAutoSvcIxOv5Rlwgl
  identifier: NGPipeAutoSvcIxOv5Rlwgl
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqpmAGv8lQF
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
