infrastructureDefinition:
  name: NGPipeAutoty2r78vUHH
  identifier: NGPipeAutoty2r78vUHH
  environmentRef: NGPipeAutorXetmJJ0Nm
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
