environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvco9kEm6ogIT
  identifier: NGPipeAutoBGAHfJy4Vd
  tags: {}
  name: NGPipeAutoBGAHfJy4Vd
  type: PreProduction
