template:
  name: NGPipeAutoStepTempN9TfC0XwGc
  identifier: NGPipeAutoStepTempN9TfC0XwGc
  projectIdentifier: NGPipeAutoPipelineSvczuMGraajJ8
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Step
  tags: {}
  spec:
    timeout: 10m
    type: ShellScript
    spec:
      shell: Bash
      onDelegate: true
      source:
        type: Inline
        spec:
          script: echo Hello
      environmentVariables: []
      outputVariables: []
