environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraFlbGm5NRGb
  identifier: NGPipeAutogtjIymeK5K
  tags: {}
  name: NGPipeAutogtjIymeK5K
  type: PreProduction
