environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcwkozZhvNMJ
  identifier: NGPipeAutoCFYxcOtMlr
  tags: {}
  name: NGPipeAutoCFYxcOtMlr
  type: PreProduction
