service:
  name: NGPipeAutoSvc65PWQQYnHG
  identifier: NGPipeAutoSvc65PWQQYnHG
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVQszCSuKM1
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
      - manifest:
          identifier: k8s
          type: K8sManifest
          spec:
            store:
              type: Harness
              spec:
                files:
                - account:/K8s/templates
            valuesPaths:
            - account:/K8s/values.yaml
            skipResourceVersioning: false
            enableDeclarativeRollback: false
      artifacts:
        primary:
          primaryArtifactRef: artifactId
          sources:
          - spec:
              connectorRef: org.GCRConnectorForAutomationTest
              imagePath: qa-target/todolist-sample
              tag: <+input>
              registryHostname: us.gcr.io
            identifier: artifactId
            type: Gcr
  gitOpsEnabled: false
