pipeline:
  name: childPipelineUsingPipelineTemplate
  identifier: childPipelineven12
  tags: {}
  template:
    templateRef: pipelineTemplatezXrB4
    versionLabel: "v1"
    gitBranch: main-patch
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
