pipeline:
  name: childPipelineUsingPipelineTemplate
  identifier: childPipelineAtaOS
  tags: {}
  template:
    templateRef: pipelineTemplateL4Ocd
    versionLabel: "v1"
    gitBranch: main-patch
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
