pipeline:
  name: childPipelineUsingPipelineTemplate
  identifier: childPipelinefevDi
  tags: {}
  template:
    templateRef: pipelineTemplateEO9jf
    versionLabel: "v1"
    gitBranch: main-patch
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
