pipeline:
  name: parentPipeline
  identifier: parentPipelineqKmyX
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Pipeline
        spec:
          org: Simlified_Git_sync
          pipeline: childPipeline06kga
          project: SimplifiedGitSync_Do_Not_Delete
