pipeline:
  name: pl_auto_pipeline_dJolP
  identifier: pl_auto_pipeline_dJolP
  template:
    templateRef: account.pl_auto_pipeline_A6sM2
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync