pipeline:
  name: pl_auto_pipeline_Vpukh
  identifier: pl_auto_pipeline_Vpukh
  template:
    templateRef: account.pl_auto_pipeline_DGLeY
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync